#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PersonelTakip")]
	public partial class PersonnalDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPozisyon(Pozisyon instance);
    partial void UpdatePozisyon(Pozisyon instance);
    partial void DeletePozisyon(Pozisyon instance);
    partial void InsertPersonel(Personel instance);
    partial void UpdatePersonel(Personel instance);
    partial void DeletePersonel(Personel instance);
    partial void InsertMaaş(Maaş instance);
    partial void UpdateMaaş(Maaş instance);
    partial void DeleteMaaş(Maaş instance);
    partial void InsertİzinDurumu(İzinDurumu instance);
    partial void UpdateİzinDurumu(İzinDurumu instance);
    partial void DeleteİzinDurumu(İzinDurumu instance);
    partial void Insertİzin(İzin instance);
    partial void Updateİzin(İzin instance);
    partial void Deleteİzin(İzin instance);
    partial void InsertİşDurumu(İşDurumu instance);
    partial void UpdateİşDurumu(İşDurumu instance);
    partial void DeleteİşDurumu(İşDurumu instance);
    partial void Insertİş(İş instance);
    partial void Updateİş(İş instance);
    partial void Deleteİş(İş instance);
    partial void InsertDepartman(Departman instance);
    partial void UpdateDepartman(Departman instance);
    partial void DeleteDepartman(Departman instance);
    partial void InsertAylar(Aylar instance);
    partial void UpdateAylar(Aylar instance);
    partial void DeleteAylar(Aylar instance);
    #endregion
		
		public PersonnalDataClassesDataContext() : 
				base(global::DAL.Properties.Settings.Default.PersonelTakipConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PersonnalDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonnalDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonnalDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PersonnalDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Pozisyon> Pozisyons
		{
			get
			{
				return this.GetTable<Pozisyon>();
			}
		}
		
		public System.Data.Linq.Table<Personel> Personels
		{
			get
			{
				return this.GetTable<Personel>();
			}
		}
		
		public System.Data.Linq.Table<Maaş> Maaşs
		{
			get
			{
				return this.GetTable<Maaş>();
			}
		}
		
		public System.Data.Linq.Table<İzinDurumu> İzinDurumus
		{
			get
			{
				return this.GetTable<İzinDurumu>();
			}
		}
		
		public System.Data.Linq.Table<İzin> İzins
		{
			get
			{
				return this.GetTable<İzin>();
			}
		}
		
		public System.Data.Linq.Table<İşDurumu> İşDurumus
		{
			get
			{
				return this.GetTable<İşDurumu>();
			}
		}
		
		public System.Data.Linq.Table<İş> İşs
		{
			get
			{
				return this.GetTable<İş>();
			}
		}
		
		public System.Data.Linq.Table<Departman> Departmans
		{
			get
			{
				return this.GetTable<Departman>();
			}
		}
		
		public System.Data.Linq.Table<Aylar> Aylars
		{
			get
			{
				return this.GetTable<Aylar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pozisyon")]
	public partial class Pozisyon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _PozisyonAd;
		
		private int _DepartmanId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPozisyonAdChanging(string value);
    partial void OnPozisyonAdChanged();
    partial void OnDepartmanIdChanging(int value);
    partial void OnDepartmanIdChanged();
    #endregion
		
		public Pozisyon()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PozisyonAd
		{
			get
			{
				return this._PozisyonAd;
			}
			set
			{
				if ((this._PozisyonAd != value))
				{
					this.OnPozisyonAdChanging(value);
					this.SendPropertyChanging();
					this._PozisyonAd = value;
					this.SendPropertyChanged("PozisyonAd");
					this.OnPozisyonAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanId", DbType="Int NOT NULL")]
		public int DepartmanId
		{
			get
			{
				return this._DepartmanId;
			}
			set
			{
				if ((this._DepartmanId != value))
				{
					this.OnDepartmanIdChanging(value);
					this.SendPropertyChanging();
					this._DepartmanId = value;
					this.SendPropertyChanged("DepartmanId");
					this.OnDepartmanIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Personel")]
	public partial class Personel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _UserNo;
		
		private string _Ad;
		
		private string _Soyad;
		
		private string _Resim;
		
		private int _DepartmanId;
		
		private int _PozisyonId;
		
		private int _Maaş;
		
		private System.Nullable<System.DateTime> _DoğumTarihi;
		
		private string _Password;
		
		private string _Adres;
		
		private bool _İşAdmin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUserNoChanging(int value);
    partial void OnUserNoChanged();
    partial void OnAdChanging(string value);
    partial void OnAdChanged();
    partial void OnSoyadChanging(string value);
    partial void OnSoyadChanged();
    partial void OnResimChanging(string value);
    partial void OnResimChanged();
    partial void OnDepartmanIdChanging(int value);
    partial void OnDepartmanIdChanged();
    partial void OnPozisyonIdChanging(int value);
    partial void OnPozisyonIdChanged();
    partial void OnMaaşChanging(int value);
    partial void OnMaaşChanged();
    partial void OnDoğumTarihiChanging(System.Nullable<System.DateTime> value);
    partial void OnDoğumTarihiChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnİşAdminChanging(bool value);
    partial void OnİşAdminChanged();
    #endregion
		
		public Personel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserNo", DbType="Int NOT NULL")]
		public int UserNo
		{
			get
			{
				return this._UserNo;
			}
			set
			{
				if ((this._UserNo != value))
				{
					this.OnUserNoChanging(value);
					this.SendPropertyChanging();
					this._UserNo = value;
					this.SendPropertyChanged("UserNo");
					this.OnUserNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ad
		{
			get
			{
				return this._Ad;
			}
			set
			{
				if ((this._Ad != value))
				{
					this.OnAdChanging(value);
					this.SendPropertyChanging();
					this._Ad = value;
					this.SendPropertyChanged("Ad");
					this.OnAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyad", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Soyad
		{
			get
			{
				return this._Soyad;
			}
			set
			{
				if ((this._Soyad != value))
				{
					this.OnSoyadChanging(value);
					this.SendPropertyChanging();
					this._Soyad = value;
					this.SendPropertyChanged("Soyad");
					this.OnSoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Resim", DbType="NVarChar(MAX)")]
		public string Resim
		{
			get
			{
				return this._Resim;
			}
			set
			{
				if ((this._Resim != value))
				{
					this.OnResimChanging(value);
					this.SendPropertyChanging();
					this._Resim = value;
					this.SendPropertyChanged("Resim");
					this.OnResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanId", DbType="Int NOT NULL")]
		public int DepartmanId
		{
			get
			{
				return this._DepartmanId;
			}
			set
			{
				if ((this._DepartmanId != value))
				{
					this.OnDepartmanIdChanging(value);
					this.SendPropertyChanging();
					this._DepartmanId = value;
					this.SendPropertyChanged("DepartmanId");
					this.OnDepartmanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PozisyonId", DbType="Int NOT NULL")]
		public int PozisyonId
		{
			get
			{
				return this._PozisyonId;
			}
			set
			{
				if ((this._PozisyonId != value))
				{
					this.OnPozisyonIdChanging(value);
					this.SendPropertyChanging();
					this._PozisyonId = value;
					this.SendPropertyChanged("PozisyonId");
					this.OnPozisyonIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maaş", DbType="Int NOT NULL")]
		public int Maaş
		{
			get
			{
				return this._Maaş;
			}
			set
			{
				if ((this._Maaş != value))
				{
					this.OnMaaşChanging(value);
					this.SendPropertyChanging();
					this._Maaş = value;
					this.SendPropertyChanged("Maaş");
					this.OnMaaşChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DoğumTarihi", DbType="Date")]
		public System.Nullable<System.DateTime> DoğumTarihi
		{
			get
			{
				return this._DoğumTarihi;
			}
			set
			{
				if ((this._DoğumTarihi != value))
				{
					this.OnDoğumTarihiChanging(value);
					this.SendPropertyChanging();
					this._DoğumTarihi = value;
					this.SendPropertyChanged("DoğumTarihi");
					this.OnDoğumTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşAdmin", DbType="Bit NOT NULL")]
		public bool İşAdmin
		{
			get
			{
				return this._İşAdmin;
			}
			set
			{
				if ((this._İşAdmin != value))
				{
					this.OnİşAdminChanging(value);
					this.SendPropertyChanging();
					this._İşAdmin = value;
					this.SendPropertyChanged("İşAdmin");
					this.OnİşAdminChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Maaş")]
	public partial class Maaş : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelId;
		
		private int _Miktar;
		
		private int _Yıl;
		
		private int _AyId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIdChanging(int value);
    partial void OnPersonelIdChanged();
    partial void OnMiktarChanging(int value);
    partial void OnMiktarChanged();
    partial void OnYılChanging(int value);
    partial void OnYılChanged();
    partial void OnAyIdChanging(int value);
    partial void OnAyIdChanged();
    #endregion
		
		public Maaş()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelId", DbType="Int NOT NULL")]
		public int PersonelId
		{
			get
			{
				return this._PersonelId;
			}
			set
			{
				if ((this._PersonelId != value))
				{
					this.OnPersonelIdChanging(value);
					this.SendPropertyChanging();
					this._PersonelId = value;
					this.SendPropertyChanged("PersonelId");
					this.OnPersonelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Miktar", DbType="Int NOT NULL")]
		public int Miktar
		{
			get
			{
				return this._Miktar;
			}
			set
			{
				if ((this._Miktar != value))
				{
					this.OnMiktarChanging(value);
					this.SendPropertyChanging();
					this._Miktar = value;
					this.SendPropertyChanged("Miktar");
					this.OnMiktarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yıl", DbType="Int NOT NULL")]
		public int Yıl
		{
			get
			{
				return this._Yıl;
			}
			set
			{
				if ((this._Yıl != value))
				{
					this.OnYılChanging(value);
					this.SendPropertyChanging();
					this._Yıl = value;
					this.SendPropertyChanged("Yıl");
					this.OnYılChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AyId", DbType="Int NOT NULL")]
		public int AyId
		{
			get
			{
				return this._AyId;
			}
			set
			{
				if ((this._AyId != value))
				{
					this.OnAyIdChanging(value);
					this.SendPropertyChanging();
					this._AyId = value;
					this.SendPropertyChanged("AyId");
					this.OnAyIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İzinDurumu")]
	public partial class İzinDurumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _İzinDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnİzinDurumAdChanging(string value);
    partial void OnİzinDurumAdChanged();
    #endregion
		
		public İzinDurumu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İzinDurumAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string İzinDurumAd
		{
			get
			{
				return this._İzinDurumAd;
			}
			set
			{
				if ((this._İzinDurumAd != value))
				{
					this.OnİzinDurumAdChanging(value);
					this.SendPropertyChanging();
					this._İzinDurumAd = value;
					this.SendPropertyChanged("İzinDurumAd");
					this.OnİzinDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İzin")]
	public partial class İzin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelId;
		
		private System.DateTime _İzinBaşlamaTarihi;
		
		private System.DateTime _İzinBitişTarihi;
		
		private string _Açıklama;
		
		private int _Süre;
		
		private int _İzinDurumId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIdChanging(int value);
    partial void OnPersonelIdChanged();
    partial void OnİzinBaşlamaTarihiChanging(System.DateTime value);
    partial void OnİzinBaşlamaTarihiChanged();
    partial void OnİzinBitişTarihiChanging(System.DateTime value);
    partial void OnİzinBitişTarihiChanged();
    partial void OnAçıklamaChanging(string value);
    partial void OnAçıklamaChanged();
    partial void OnSüreChanging(int value);
    partial void OnSüreChanged();
    partial void OnİzinDurumIdChanging(int value);
    partial void OnİzinDurumIdChanged();
    #endregion
		
		public İzin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelId", DbType="Int NOT NULL")]
		public int PersonelId
		{
			get
			{
				return this._PersonelId;
			}
			set
			{
				if ((this._PersonelId != value))
				{
					this.OnPersonelIdChanging(value);
					this.SendPropertyChanging();
					this._PersonelId = value;
					this.SendPropertyChanged("PersonelId");
					this.OnPersonelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İzinBaşlamaTarihi", DbType="Date NOT NULL")]
		public System.DateTime İzinBaşlamaTarihi
		{
			get
			{
				return this._İzinBaşlamaTarihi;
			}
			set
			{
				if ((this._İzinBaşlamaTarihi != value))
				{
					this.OnİzinBaşlamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._İzinBaşlamaTarihi = value;
					this.SendPropertyChanged("İzinBaşlamaTarihi");
					this.OnİzinBaşlamaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İzinBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime İzinBitişTarihi
		{
			get
			{
				return this._İzinBitişTarihi;
			}
			set
			{
				if ((this._İzinBitişTarihi != value))
				{
					this.OnİzinBitişTarihiChanging(value);
					this.SendPropertyChanging();
					this._İzinBitişTarihi = value;
					this.SendPropertyChanged("İzinBitişTarihi");
					this.OnİzinBitişTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Açıklama", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Açıklama
		{
			get
			{
				return this._Açıklama;
			}
			set
			{
				if ((this._Açıklama != value))
				{
					this.OnAçıklamaChanging(value);
					this.SendPropertyChanging();
					this._Açıklama = value;
					this.SendPropertyChanged("Açıklama");
					this.OnAçıklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Süre", DbType="Int NOT NULL")]
		public int Süre
		{
			get
			{
				return this._Süre;
			}
			set
			{
				if ((this._Süre != value))
				{
					this.OnSüreChanging(value);
					this.SendPropertyChanging();
					this._Süre = value;
					this.SendPropertyChanged("Süre");
					this.OnSüreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İzinDurumId", DbType="Int NOT NULL")]
		public int İzinDurumId
		{
			get
			{
				return this._İzinDurumId;
			}
			set
			{
				if ((this._İzinDurumId != value))
				{
					this.OnİzinDurumIdChanging(value);
					this.SendPropertyChanging();
					this._İzinDurumId = value;
					this.SendPropertyChanged("İzinDurumId");
					this.OnİzinDurumIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İşDurumu")]
	public partial class İşDurumu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _İşDurumAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnİşDurumAdChanging(string value);
    partial void OnİşDurumAdChanged();
    #endregion
		
		public İşDurumu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşDurumAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string İşDurumAd
		{
			get
			{
				return this._İşDurumAd;
			}
			set
			{
				if ((this._İşDurumAd != value))
				{
					this.OnİşDurumAdChanging(value);
					this.SendPropertyChanging();
					this._İşDurumAd = value;
					this.SendPropertyChanged("İşDurumAd");
					this.OnİşDurumAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.İş")]
	public partial class İş : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private int _PersonelId;
		
		private string _Başlık;
		
		private string _İçerik;
		
		private System.DateTime _İşBaşlamaTarihi;
		
		private System.DateTime _İşBitişTarihi;
		
		private int _İşDurumId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPersonelIdChanging(int value);
    partial void OnPersonelIdChanged();
    partial void OnBaşlıkChanging(string value);
    partial void OnBaşlıkChanged();
    partial void OnİçerikChanging(string value);
    partial void OnİçerikChanged();
    partial void OnİşBaşlamaTarihiChanging(System.DateTime value);
    partial void OnİşBaşlamaTarihiChanged();
    partial void OnİşBitişTarihiChanging(System.DateTime value);
    partial void OnİşBitişTarihiChanged();
    partial void OnİşDurumIdChanging(int value);
    partial void OnİşDurumIdChanged();
    #endregion
		
		public İş()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersonelId", DbType="Int NOT NULL")]
		public int PersonelId
		{
			get
			{
				return this._PersonelId;
			}
			set
			{
				if ((this._PersonelId != value))
				{
					this.OnPersonelIdChanging(value);
					this.SendPropertyChanging();
					this._PersonelId = value;
					this.SendPropertyChanged("PersonelId");
					this.OnPersonelIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Başlık", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Başlık
		{
			get
			{
				return this._Başlık;
			}
			set
			{
				if ((this._Başlık != value))
				{
					this.OnBaşlıkChanging(value);
					this.SendPropertyChanging();
					this._Başlık = value;
					this.SendPropertyChanged("Başlık");
					this.OnBaşlıkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İçerik", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string İçerik
		{
			get
			{
				return this._İçerik;
			}
			set
			{
				if ((this._İçerik != value))
				{
					this.OnİçerikChanging(value);
					this.SendPropertyChanging();
					this._İçerik = value;
					this.SendPropertyChanged("İçerik");
					this.OnİçerikChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşBaşlamaTarihi", DbType="Date NOT NULL")]
		public System.DateTime İşBaşlamaTarihi
		{
			get
			{
				return this._İşBaşlamaTarihi;
			}
			set
			{
				if ((this._İşBaşlamaTarihi != value))
				{
					this.OnİşBaşlamaTarihiChanging(value);
					this.SendPropertyChanging();
					this._İşBaşlamaTarihi = value;
					this.SendPropertyChanged("İşBaşlamaTarihi");
					this.OnİşBaşlamaTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşBitişTarihi", DbType="Date NOT NULL")]
		public System.DateTime İşBitişTarihi
		{
			get
			{
				return this._İşBitişTarihi;
			}
			set
			{
				if ((this._İşBitişTarihi != value))
				{
					this.OnİşBitişTarihiChanging(value);
					this.SendPropertyChanging();
					this._İşBitişTarihi = value;
					this.SendPropertyChanged("İşBitişTarihi");
					this.OnİşBitişTarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_İşDurumId", DbType="Int NOT NULL")]
		public int İşDurumId
		{
			get
			{
				return this._İşDurumId;
			}
			set
			{
				if ((this._İşDurumId != value))
				{
					this.OnİşDurumIdChanging(value);
					this.SendPropertyChanging();
					this._İşDurumId = value;
					this.SendPropertyChanged("İşDurumId");
					this.OnİşDurumIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Departman")]
	public partial class Departman : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DepartmanAd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDepartmanAdChanging(string value);
    partial void OnDepartmanAdChanged();
    #endregion
		
		public Departman()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmanAd", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string DepartmanAd
		{
			get
			{
				return this._DepartmanAd;
			}
			set
			{
				if ((this._DepartmanAd != value))
				{
					this.OnDepartmanAdChanging(value);
					this.SendPropertyChanging();
					this._DepartmanAd = value;
					this.SendPropertyChanged("DepartmanAd");
					this.OnDepartmanAdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Aylar")]
	public partial class Aylar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnAyChanging(string value);
    partial void OnAyChanged();
    #endregion
		
		public Aylar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ay", DbType="NChar(20)")]
		public string Ay
		{
			get
			{
				return this._Ay;
			}
			set
			{
				if ((this._Ay != value))
				{
					this.OnAyChanging(value);
					this.SendPropertyChanging();
					this._Ay = value;
					this.SendPropertyChanged("Ay");
					this.OnAyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
