<?xml version="1.0" encoding="utf-8"?><Database Name="PersonelTakip" Class="PersonnalDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-97H79MIN;Initial Catalog=PersonelTakip;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="PersonelTakipConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Pozisyon" Member="Pozisyons">
    <Type Name="Pozisyon">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PozisyonAd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DepartmanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Personel" Member="Personels">
    <Type Name="Personel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserNo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Soyad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Resim" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DepartmanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PozisyonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Maaş" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DoğumTarihi" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Adres" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="İşAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Maaş" Member="Maaşs">
    <Type Name="Maaş">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Miktar" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Yıl" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.İzinDurumu" Member="İzinDurumus">
    <Type Name="İzinDurumu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="İzinDurumAd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.İzin" Member="İzins">
    <Type Name="İzin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="İzinBaşlamaTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="İzinBitişTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Açıklama" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Süre" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="İzinDurumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.İşDurumu" Member="İşDurumus">
    <Type Name="İşDurumu">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="İşDurumAd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.İş" Member="İşs">
    <Type Name="İş">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PersonelId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Başlık" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="İçerik" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="İşBaşlamaTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="İşBitişTarihi" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="İşDurumId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Departman" Member="Departmans">
    <Type Name="Departman">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepartmanAd" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Aylar" Member="Aylars">
    <Type Name="Aylar">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ay" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>